version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
        volumes:
            - "esdata:/usr/share/elasticsearch/data"
        networks:
            - elastic
        ports:
            - 9200:9200
            - 9300:9300
        restart: always

    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.2
        container_name: kibana
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch:9200/
        links:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            - elastic

    logstash:
        image: docker.elastic.co/logstash/logstash:7.15.2
        container_name: logstash
        environment:
            - node.name=logstash
        volumes:
            - "./logstash/pipeline:/usr/share/logstash/pipeline"
            - "./logstash/data:/tmp/data"
        links:
            - elasticsearch
        networks:
            - elastic
        restart: always

networks:
    elastic: null

volumes:
    esdata: null
